apps/accounts/urls.py
from django.urls import path

from apps.accounts import views

app_name = 'account'

urlpatterns = [
    path('login/', views.log_in, name='login'),
    path('signup/', views.sign_up, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    # path('users/', views.view_all_users, name='view_all_users'),
    path('users/<username>/', views.view_profile, name='view_profile'),
]

apps/core/urls.py
from django.urls import path

from apps.core import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('add-new/', views.add_new, name='add_new'),
    path('edit/<int:id>', views.edit, name='edit'),
    path('list-view/', views.list_view, name='list_view'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('log_location/', views.log_location, name="log_location"),
    path('address/', views.address, name="log_location"),
]

wildlife_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('apps.core.urls')),
    path('account/', include('apps.accounts.urls')),
    path('admin/', admin.site.urls),

] + static( # Add in uploaded media files
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)


# Add in debug toolbar if necessary
if settings.DEBUG:
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

apps/accounts/models.py
import hashlib

from django.db import models
from django.contrib.auth.models import AbstractUser

# Custom User class which extends built-in User. Presently, just adds a "bio"
# and a gravatar method. Feel free to add your own new fields here!

class User(AbstractUser):

    bio = models.TextField()

    def gravatar(self, size=None):
        GRAVATAR_URL = 'https://gravatar.com/avatar/%s?d=identicon%s'
        email = str(self.email).strip().lower()
        digest = hashlib.md5(email.encode('utf-8')).hexdigest()

        if size:
            size_str = '&s=%i' % size
        else:
            size_str = ''

        return GRAVATAR_URL % (digest, size_str)

apps/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms

from apps.accounts.models import User

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'email',
            'bio',
        )

class SignupForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = (
            'username',
            'email',
            'password1',
            'password2',
        )

apps/accounts/views.py
from django.shortcuts import render
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from apps.accounts.forms import UserEditForm, SignupForm
from apps.accounts.models import User
from apps.core.models import Report


def log_in(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect('core:home')
    else:
        form = AuthenticationForm()

    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


def sign_up(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()

            # Log-in the user right away
            messages.success(request, 'Account created successfully. Welcome!')
            login(request, user)
            return redirect('core:home')
    else:
        form = SignupForm()

    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


def logout_view(request):
    logout(request)
    messages.success(request, 'Logged out.')
    return redirect('core:home')


def view_all_users(request):
    all_users = User.objects.all()
    context = {
        'users': all_users,
    }
    return render(request, 'accounts/view_all_users.html', context)


def view_profile(request, username):
    user = User.objects.get(username=username)

    if request.user == user:
        is_viewing_self = True
    else:
        is_viewing_self = False

    reports_by_user = Report.objects.filter(user=user).order_by('-created')

    context = {
        'user': user,
        'is_viewing_self': is_viewing_self,
        'reports': reports_by_user,
    }
    return render(request, 'accounts/profile_page.html', context)

@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = UserEditForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('core:home')
    else:
        form = UserEditForm(instance=request.user)

    context = {
        'form': form,
    }
    return render(request, 'accounts/edit_profile.html', context)

apps/accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}
    Edit Profile
{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <h1 class="text-center">{{ request.user }}</h1>
        <h3>Edit information</h3>
        <p><strong>Note:</strong> Your avatar is based on your email. Change
        your avatar at <a href="https://en.gravatar.com/">Gravatar.com</a></p>
        <form class="form-signin" method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class="btn btn-lg btn-succesa btn-block text-uppercase">Save</button>
        </form>
    </div>
</div>
{% endblock %}

apps/accounts/templates/accounts/form_snippet.html
{% load bootstrap4 %}

<div class="row">
    <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
            <div class="card-body">
                <h5 class="card-title text-center">{{ form_title }}</h5>
                <form class="form-signin" method="POST">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">{{ form_title }}</button>
                </form>
            </div>
        </div>
    </div>
</div>

apps/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

{% include "accounts/form_snippet.html" with form_title="Log In" %}

{% endblock %}

apps/accounts/templates/accounts/profile_page.html
{% extends 'base.html' %}

{% block title %}
@{{ user.username }}
{% endblock title %}
{% load tz %}

{% load static %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-2" style="height:100vh;">
      <div class="profile">
        <h3>@{{ user.username }}</h3>
        <img class="img-fluid prof_img" src="{{ user.gravatar }}" />
        <p><strong>{{ user.first_name }} {{ user.last_name }}</strong></p>
        <p>{{ user.bio }}</p>
        {% if is_viewing_self %}
        <a href="{% url 'account:edit_profile' %}">Edit</a>
        {% endif %}
      </div>
    </div>
    <div class="col-md-10">
      {% for report in reports %}
      <div class="card user_report_card">
        <div class="row">
          <div class="col">
            <h4>{{report.summary}}</h4>
          </div>
        </div>
        <div class="row">
          <div class="col-4">
            {% if report.image %}
            <img class="img-thumbnail" src="{{ report.image.url }}" alt="{{ report.summary }}">
            {% else %}
            <img class="img-thumbnail no-image" src="{% static 'images/noImageAvailable.png' %}" alt="(No image available)">
            {% endif %}
          </div>
          <div class="col-8">
            <div class="row">
              <div class="col">
                <div class="report_date">{{ report.created|timezone:"US/Pacific"  }}</div>
                <div class="report_text">{{ report.detailed_description}}</div>
              </div>
            </div>
          </div>
        </div>
        <div class="row" style="margin-bottom:5px;">
          <div class="col-9">
          </div>
          <div class="col-1">
            <form action="{% url 'core:edit' report.id %}" method="GET">
              <button type="submit" class="btn btn-info">Edit</button>
            </form>
          </div>
          <div class="col-1">
            <form action="{% url 'core:delete' report.id %}" onclick="return confirm('Are you sure you want to delete?')" \ method="GET">
              <button type="submit" class="btn btn-danger">Delete</button>
            </form>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>


{% endblock %}

apps/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}

{% include "accounts/form_snippet.html" with form_title="Sign Up" %}

{% endblock %}

apps/accounts/templates/accounts/view_all_users.html
{% extends 'base.html' %}

{% block title %}
    Users
{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <h1>Users</h1>
        {% for user in users %}
            <a href="{% url 'account:view_profile' user.username %}">
                <div class="card card-signin card-user my-5">
                    <img src="{{ user.gravatar }}" />
                    <h5 class="card-title text-center">@{{ user.username }}</h5>
                </div>
            </a>
        {% endfor %}
    </div>
</div>
{% endblock %}