apps/accounts/urls.py
from django.urls import path

from apps.accounts import views

app_name = 'account'

urlpatterns = [
    path('login/', views.log_in, name='login'),
    path('signup/', views.sign_up, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    # path('users/', views.view_all_users, name='view_all_users'),
    path('users/<username>/', views.view_profile, name='view_profile'),
]

apps/core/urls.py
from django.urls import path

from apps.core import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('add-new/', views.add_new, name='add_new'),
    path('edit/<int:id>', views.edit, name='edit'),
    path('list-view/', views.list_view, name='list_view'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('log_location/', views.log_location, name="log_location"),
    path('address/', views.address, name="log_location"),
]

wildlife_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('apps.core.urls')),
    path('account/', include('apps.accounts.urls')),
    path('admin/', admin.site.urls),

] + static( # Add in uploaded media files
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)


# Add in debug toolbar if necessary
if settings.DEBUG:
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

apps/core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models.signals import post_delete
from django.dispatch import receiver


class Report(models.Model):
    """Define Report."""

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    summary = models.CharField(max_length=100)

    animals = (('BEAR', 'Bear'),
               ('BOBCAT', 'Bobcat'),
               ('CAT', 'Cat'),
               ('COYOTE', 'Coyote'),
               ('DEER', 'Deer'),
               ('EAGLE', 'Eagle'),
               ('EL CHUPACABRA', 'El Chupacabra'),
               ('MOUNTAIN LION', 'Mountain Lion'),
               ('WOLF', 'Wolf'),
               ('OTHER', 'Other'))

    animal_type = models.CharField(max_length=20,
                                   choices=animals,
                                   default='COYOTEE',
                                   )
    lat_position = models.DecimalField(max_digits=10, decimal_places=7)
    lon_position = models.DecimalField(max_digits=10, decimal_places=7)
    detailed_description = models.TextField(max_length=1000)
    # sighting_time = models.DateTimeField(auto_now_add=False)
    created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    image = models.FileField(upload_to='submitted_images/',
                             null=True,
                             blank=True)


@receiver(post_delete, sender=Report)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False)

apps/core/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django import forms
from .models import Report
import json
from geopy.geocoders import MapBox
import os
import pytz
from django.utils import timezone



class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ['summary',
                  'animal_type',
                  # 'sighting_time', TODO Implement time input.
                  'lat_position',
                  'lon_position',
                  'detailed_description',
                  'image',
                  ]
        widgets = {'text': forms.Textarea()}


def home(request):
    reports = Report.objects.all().order_by('-created')

    loc_oakland = {'lat_position': 37.8, 'lon_position': -122.27, }
    map_zoom_level = 10

    context = {'example_context_variable': 'Change me.',
               'vlat': loc_oakland['lat_position'],
               'vlon': loc_oakland['lon_position'],
               'view': map_zoom_level,
               'drag': 'false',
               'page': 'main',
               'reports': reports,
               }

    return render(request, 'pages/home.html', context)


def about_page(request):
    
    if report.user == request.user:
        messages.error(request, 'Could not confirm if this record was filed \
                                    by the current user.')
        return redirect('/')

    report.delete() 
    messages.warning(request, f"Deleted the report of \'{report.type}\'") 
    
    return redirect('/account/users/' + request.user.username)
   


def add_new(request):
    """Add new report to database."""
    if request.user.is_anonymous:
        context = {}
        return render(request, 'pages/login_required.html', context)

    if 'lat' not in request.session.keys():
        loc_oakland = {'lat_position': 37.8, 'lon_position': -122.27, }
        request.session['lat'] = loc_oakland['lat_position']
        request.session['lon'] = loc_oakland['lon_position']

    if request.method == 'POST':
        form = ReportForm(request.POST, request.FILES)
        if form.is_valid():
            report = form.save(commit=False)
            report.user = request.user
            report.save()
            return redirect('/')

    else:
        reports = [{'lat_position': request.session['lat'],
                    'lon_position': request.session['lon'],
                    'text': '',
                    }]
        form = ReportForm(initial={'lat_position': request.session['lat'],
                                   'lon_position': request.session['lon']
                                   })
        context = {'form': form,
                   'reports': reports,
                   'vlat': request.session['lat'],
                   'vlon': request.session['lon'],
                   'view': '16',
                   'drag': 'true',
                   'page': 'report',
                   }
        return render(request, 'pages/add_report.html', context)


def log_location(request):
    """Log User Location from Browser Geolocation in Session."""
    if request.method == "POST":
        loc = json.loads(request.body)
        request.session['lat'] = round(loc['lat'], 7)
        request.session['lon'] = round(loc['lon'], 7)
        return HttpResponse(request)
    else:
        return redirect('/')

@login_required
def edit(request, id):
    report = Report.objects.get(id=id)

    if report.user != request.user:
        messages.error(request, 'Could not confirm if this record was filed \
                                    by the current user.')
        return redirect('/')

    if request.method == "POST":
        form = ReportForm(request.POST, request.FILES, instance=report)
        if form.is_valid():
            form.save()
            messages.info(request, 'Your update was saved!')
            return redirect('/account/users/' + request.user.username)
        else:
            messages.error(request, 'Form Validation Error at the server')
            return redirect('/')

    form = ReportForm(instance=report)
    context = {'form': form,
               'reports': [report],
               'vlat': report.lat_position,
               'vlon': report.lon_position,
               'view': '16',
               'drag': 'true',
               'page': 'report',
               }

    return render(request, 'pages/add_report.html', context)


def list_view(request):
    context = {
    }
    
    return render(request, 'pages/about.html', context)


@login_required
def delete(request, id):
    report = Report.objects.get(id=id)


    if report.user != request.user:
        messages.error(request, 'Could not confirm if this record was filed \
                                    by the current user.')
        return redirect('/')

    report.delete()
    messages.warning(request, f"Deleted the report of \'{report.summary}\'")

    return redirect('/account/users/' + request.user.username)


def address(request):
    """Return lat/lon for input address via json fetch."""
    if request.method == "POST":
        print(request.body.decode('utf-8'))
        address = '{address}, {city}, {state} {zip}'.format(
            **json.loads(request.body.decode('utf-8')))
        geolocator = MapBox(api_key=os.getenv('MB_TOKEN'))
        location = geolocator.geocode(address)
        new_loc = {'lat_position': location.latitude,
                   'lon_position': location.longitude,
                   }
        return JsonResponse(new_loc)
    else:
        return redirect('/')

apps/core/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

apps/core/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>
    {% block title %}
    My Site
    {% endblock title %}
  </title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">


  <link href="{% static 'css/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/signinform.css' %}" rel="stylesheet">

  <!-- Add your custom CSS to this file -->
  <link href="{% static 'css/custom.css' %}" rel="stylesheet">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <!-- Leaflet CSS -->
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css" integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ==" crossorigin="" />
  <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js" integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew==" crossorigin=""></script>

</head>

<body>
  <nav class="navbar navbar-expand-md">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">
        <img style="width: 60px; border-radius: 25%;" src="{% static 'images/paw.png' %}" />
      </a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon">
          ☰
        </span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link nav-link-color" href="{% url 'core:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link nav-link-color" href="{% url 'core:about' %}">About</a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link nav-link-color" href="{% url 'account:view_profile' request.user %}">
              <img src="{{ user.gravatar }}" class="navbar-avatar" />
              {{ request.user }}
            </a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link nav-link-color" href="{% url 'account:logout' %}">Sign Out</a>
          </li>

          {% else %}
          <li class="nav-item">
            <a id="log-in-link" class="nav-link nav-link-color" href="{% url 'account:login' %}">Log In</a>
          </li>
          <li class="nav-item">
            <a id="log-in-link" class="nav-link nav-link-color" href="{% url 'account:signup' %}">Sign up</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  {% block content %}
  {% endblock content %}

  <script src="{% static 'js/bootstrap/jquery-3.4.1.min.js' %}"></script>
  <script src="{% static 'js/bootstrap/bootstrap.js' %}"></script>
</body>

</html>